import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import {
  base32LowerNoPad,
  encodeAssertion,
  matrixLocalpart,
  subjectFor,
  verifyIdentityAssertion,
} from '../identity.js'

/*
 * para-idp re-implements the signature verifier and the localpart derivation
 * because it lives in a different repository from mubEZ and iM8. These vectors
 * are what stop the copies drifting: they are generated by mubEZ from its
 * reference implementation, and a failure here means a signature made on a
 * device will not verify at login.
 */

const here = dirname(fileURLToPath(import.meta.url))
const sigVectors = JSON.parse(
  readFileSync(join(here, 'identity-signature-vectors.json'), 'utf8'),
).vectors as Array<{
  seed: string
  label: string
  purpose: 'matrix-login' | 'mubez-registration'
  audience: string
  assertion: Parameters<typeof encodeAssertion>[0]
  sr25519PublicKey: string
  encoded: string
  signature: string
}>

const derivationVectors = JSON.parse(
  readFileSync(join(here, 'identity-derivation-vectors.json'), 'utf8'),
).vectors as Array<{
  seed: string
  identities: Array<{ label: string; pub: string }>
}>

const NOW = new Date('2026-08-24T12:00:30.000Z')

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2)
  for (let i = 0; i < out.length; i++) {
    out[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16)
  }
  return out
}

describe('base32', () => {
  // RFC 4648 §10, lowercased and unpadded.
  it.each([
    ['', ''],
    ['f', 'my'],
    ['fo', 'mzxq'],
    ['foo', 'mzxw6'],
    ['foob', 'mzxw6yq'],
    ['fooba', 'mzxw6ytb'],
    ['foobar', 'mzxw6ytboi'],
  ])('encodes %j as %j', (input, expected) => {
    expect(base32LowerNoPad(new TextEncoder().encode(input))).toBe(expected)
  })
})

describe('localpart derivation (CD-M1)', () => {
  it('matches the values iM8 derives for the shared seeds', () => {
    // Pinned from iM8's matrixIdentity tests. The client and the IdP must
    // agree, or a user logs in and lands in a different account.
    const expected: Record<string, { public: string; anonymous: string }> = {
      '0000000000000000000000000000000000000000000000000000000000000000': {
        public: 'k4o2lmcmitomgymtdb7y3htsthoofobo',
        anonymous: 'tksdt6ou5rbvxzeegiriy25u24pft5gz',
      },
      '0101010101010101010101010101010101010101010101010101010101010101': {
        public: '4hyygdnabmal525vs4ngqdcja7rxihxu',
        anonymous: 'cdx6xbqfawx7sqwpyvapwhwfvfu45l6f',
      },
      '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08': {
        public: 'vrj6nj2ieu5vcj77lyfa3zskcvtkftly',
        anonymous: 'uvbbhlafnltimfcsy7mlsptwdsasrt6y',
      },
    }
    for (const vector of derivationVectors) {
      for (const label of ['public', 'anonymous'] as const) {
        const identity = vector.identities.find((i) => i.label === label)!
        expect(matrixLocalpart(hexToBytes(identity.pub))).toBe(
          expected[vector.seed][label],
        )
      }
    }
  })

  it('rejects anything that is not a 32-byte key', () => {
    expect(() => matrixLocalpart(new Uint8Array(31))).toThrow(/32 bytes/)
  })
})

describe('signature verification against mubEZ vectors', () => {
  it('encodes the canonical payload byte for byte', () => {
    for (const v of sigVectors) {
      expect(new TextDecoder().decode(encodeAssertion(v.assertion))).toBe(v.encoded)
    }
  })

  it('verifies every signature mubEZ published', () => {
    for (const v of sigVectors) {
      expect(
        verifyIdentityAssertion(
          { assertion: v.assertion, signature: v.signature },
          {
            purpose: v.purpose,
            audience: v.audience,
            challenge: v.assertion.challenge,
            now: NOW,
          },
        ),
      ).toBe(true)
    }
  })

  it('derives a subject from a verified assertion', () => {
    for (const v of sigVectors) {
      expect(subjectFor(v.assertion)).toMatch(/^[a-z2-7]{32}$/)
    }
  })
})

describe('verifier rejections', () => {
  const v = sigVectors[0]
  const base = {
    purpose: v.purpose,
    audience: v.audience,
    challenge: v.assertion.challenge,
    now: NOW,
  }
  const signed = { assertion: v.assertion, signature: v.signature }

  it('refuses a registration assertion as a matrix login', () => {
    const reg = sigVectors.find((x) => x.purpose === 'mubez-registration')!
    expect(
      verifyIdentityAssertion(
        { assertion: reg.assertion, signature: reg.signature },
        { ...base, purpose: 'matrix-login', audience: reg.audience },
      ),
    ).toBe(false)
  })

  it('refuses a mismatched audience or challenge', () => {
    expect(verifyIdentityAssertion(signed, { ...base, audience: 'evil' })).toBe(false)
    expect(verifyIdentityAssertion(signed, { ...base, challenge: 'other' })).toBe(false)
  })

  it('refuses stale and future-dated assertions', () => {
    expect(
      verifyIdentityAssertion(signed, { ...base, now: new Date('2026-08-24T13:00:00Z') }),
    ).toBe(false)
    expect(
      verifyIdentityAssertion(signed, { ...base, now: new Date('2026-08-24T11:00:00Z') }),
    ).toBe(false)
  })

  it('returns false rather than throwing on hostile input', () => {
    const junk: unknown[] = [null, undefined, '', 'zz', 'ff'.repeat(64), 'gg'.repeat(64), 42, {}, []]
    for (const sig of junk) {
      for (const pub of junk) {
        expect(
          verifyIdentityAssertion(
            {
              assertion: { ...v.assertion, identityPub: String(pub) },
              signature: String(sig),
            } as never,
            base,
          ),
        ).toBe(false)
      }
    }
    for (const shape of [null, undefined, 'x', 1, [], {}, { assertion: null, signature: 'a' }]) {
      expect(verifyIdentityAssertion(shape as never, base)).toBe(false)
    }
  })
})
