packages:
  - 'services/*'
  - 'packages/*'
  - 'packages/lex/*'
  - 'packages/oauth/*'
  - 'packages/internal/*'
overrides:
  '@smithy/core': ^3.29.5
allowBuilds:
  '@bufbuild/buf': true
  '@datadog/native-appsec': true
  '@datadog/native-iast-taint-tracking': true
  '@datadog/native-metrics': true
  '@datadog/pprof': true
  '@matrix-org/matrix-sdk-crypto-nodejs': true
  '@swc/core': true
  better-sqlite3: true
  core-js: true
  dd-trace: false
  esbuild: true
  protobufjs: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
