// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts,import_extension=.js"
// @generated from file dataplane.proto (package bsky, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { UpdateNotificationSeenRequest, UpdateNotificationSeenResponse } from "./dataplane_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service bsky.Service
 */
export const Service = {
  typeName: "bsky.Service",
  methods: {
    /**
     * @generated from rpc bsky.Service.UpdateNotificationSeen
     */
    updateNotificationSeen: {
      name: "UpdateNotificationSeen",
      I: UpdateNotificationSeenRequest,
      O: UpdateNotificationSeenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

