#!/bin/bash
set -euo pipefail

# PARA Matrix Homeserver Setup
# Run once to generate Synapse config and prepare the stack.
#
# Usage:
#   ./WhatZatppa/deploy/matrix/setup.sh
#
# Prerequisites:
#   - Docker and docker compose installed
#   - .env file created from .env.example with MATRIX_* vars filled
#   - DNS A record pointing MATRIX_DOMAIN to this server

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MATRIX_COMPOSE="${SCRIPT_DIR}/../../docker-compose.matrix.yaml"
ENV_FILE="${SCRIPT_DIR}/../../.env"

echo "═══════════════════════════════════════════════════════════════"
echo "  PARA Matrix Homeserver Setup"
echo "═══════════════════════════════════════════════════════════════"

# Validate env file
if [ ! -f "$ENV_FILE" ]; then
    echo "❌ $ENV_FILE not found. Create it from .env.example first."
    exit 1
fi

# Load only MATRIX_* vars
export $(grep -E '^MATRIX_' "$ENV_FILE" | xargs) || true
export $(grep -E '^POSTGRES_' "$ENV_FILE" | xargs) || true

MATRIX_SERVER_NAME="${MATRIX_SERVER_NAME:-matrix.para.social}"
MATRIX_DOMAIN="${MATRIX_DOMAIN:-chat.para.social}"
MATRIX_DB_NAME="${MATRIX_DB_NAME:-matrix}"
POSTGRES_USER="${POSTGRES_USER:-pg}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-changeme}"

echo ""
echo "📋 Configuration:"
echo "   Server Name:  $MATRIX_SERVER_NAME"
echo "   Element URL:  https://$MATRIX_DOMAIN"
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# 1. Generate Synapse config (one-time)
# ─────────────────────────────────────────────────────────────────────────────
if [ ! -d "${SCRIPT_DIR}/synapse" ]; then
    echo "🔧 Generating Synapse configuration..."
    mkdir -p "${SCRIPT_DIR}/synapse"

    # The anonymous -v /data volume exists only for this generate run: the
    # image's start.py chowns SYNAPSE_DATA_DIR before writing config, so the
    # directory must exist even though nothing we keep is written there.
    # --rm discards it. Runtime /data is the synapse_data named volume.
    #
    # Generate with CONFIG_DIR=/config so that signing_key_path lands in this
    # directory (mounted read-only at /config at runtime), while media and other
    # state stay under /data in the named volume.
    #
    # POSTGRES_* are the variable names the image's config template reads. The
    # SYNAPSE_DB_* names in docker-compose.matrix.yaml are not recognised by it,
    # so omitting these here silently generates a SQLite config and the
    # synapse-db container goes unused.
    docker run --rm \
        -e SYNAPSE_SERVER_NAME="$MATRIX_SERVER_NAME" \
        -e SYNAPSE_REPORT_STATS=no \
        -e SYNAPSE_CONFIG_DIR=/config \
        -e SYNAPSE_DATA_DIR=/data \
        -e POSTGRES_HOST=synapse-db \
        -e POSTGRES_PORT=5432 \
        -e POSTGRES_DB="$MATRIX_DB_NAME" \
        -e POSTGRES_USER="$POSTGRES_USER" \
        -e POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
        -v "${SCRIPT_DIR}/synapse:/config" \
        -v /data \
        matrixdotorg/synapse:v1.134.0 generate

    # Nothing is appended to or edited into homeserver.yaml. Two reasons:
    #
    #   1. The generated file ends with "# vim:ft=yaml" and NO trailing
    #      newline, so `echo >>` fuses onto that comment line and silently
    #      produces invalid YAML.
    #   2. Settings edited here would be a second source of truth alongside
    #      deploy/matrix/hardening.yaml and would drift.
    #
    # Instead we write a generated overlay. Synapse merges every *.yaml in the
    # config directory in lexicographic order, so:
    #      homeserver.yaml  <  zz-para-database.yaml  <  zz-para-hardening.yaml
    # This file holds the database credentials, which is also why it lives in
    # the gitignored generated directory rather than in the tracked overlay.
    DB_OVERLAY="${SCRIPT_DIR}/synapse/zz-para-database.yaml"
    cat > "$DB_OVERLAY" <<DBEOF
# GENERATED by deploy/matrix/setup.sh — do not edit, do not commit.
# Points Synapse at the synapse-db container from docker-compose.matrix.yaml.
#
# The \`generate\` subcommand always emits a SQLite config: POSTGRES_* are read
# by the image's start-up template, not by \`generate\`. Without this overlay
# Synapse runs on SQLite while the Postgres container sits unused, and the
# retention purge jobs are not viable there.
database:
  name: psycopg2
  args:
    user: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    database: "${MATRIX_DB_NAME}"
    host: synapse-db
    port: 5432
    cp_min: 5
    cp_max: 10
DBEOF
    chmod 600 "$DB_OVERLAY"

    # Redis is deliberately NOT configured. It is only needed for a worker
    # deployment, docker-compose.matrix.yaml defines no redis service, and the
    # previous version of this script enabled it from any REDIS_HOST in .env —
    # pointing Synapse at a host that does not exist in this stack.

    echo "✅ Synapse config generated at ${SCRIPT_DIR}/synapse/"
    echo "   Hardening overlay: ${SCRIPT_DIR}/hardening.yaml (merged at runtime)"
    echo "   ⚠️  This directory now contains the signing key and secrets."
    echo "      It is gitignored — keep it that way, and back it up separately."
else
    echo "⚠️  Synapse config already exists. Skipping generation."
    echo "   Delete ${SCRIPT_DIR}/synapse/ to regenerate."
fi

# ─────────────────────────────────────────────────────────────────────────────
# 2. Generate Element Web config
# ─────────────────────────────────────────────────────────────────────────────
ELEMENT_CFG="${SCRIPT_DIR}/element-config.json"

cat > "$ELEMENT_CFG" <<EOF
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://${MATRIX_SERVER_NAME}",
            "server_name": "${MATRIX_SERVER_NAME}"
        }
    },
    "brand": "PARA Chat",
    "room_directory": {
        "servers": ["${MATRIX_SERVER_NAME}"]
    },
    "disable_custom_urls": true,
    "disable_guests": true,
    "disable_login_language_selector": false,
    "disable_3pid_login": true,
    "features": {
        "feature_threadenabled": true,
        "feature_roomlist_video_layout": false
    },
    "setting_defaults": {
        "breadcrumbs": true,
        "show_labs_settings": false
    },
    "integrations_ui_url": "",
    "integrations_rest_url": "",
    "integrations_widgets_urls": [],
    "embedded_pages": {
        "home_url": ""
    },
    "terms_and_conditions_links": [
        {
            "url": "https://para.social/tos",
            "text": "Terms of Service"
        },
        {
            "url": "https://para.social/privacy",
            "text": "Privacy Policy"
        }
    ]
}
EOF

echo "✅ Element config generated at $ELEMENT_CFG"

# ─────────────────────────────────────────────────────────────────────────────
# 3. Print federation well-known snippets
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "📡 Federation Setup Required"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "Create these files on your web server at the DOMAIN root"
echo "(e.g., served by Caddy/nginx at https://$MATRIX_SERVER_NAME):"
echo ""
echo "--- .well-known/matrix/server ---"
cat <<FED
{ "m.server": "${MATRIX_SERVER_NAME}:443" }
FED
echo ""
echo "--- .well-known/matrix/client ---"
cat <<FED
{ "m.homeserver": { "base_url": "https://${MATRIX_SERVER_NAME}" } }
FED
echo ""
echo "If $MATRIX_SERVER_NAME is the SAME host as the Synapse container,"
echo "Caddy/nginx can serve these as static files."
echo "See deploy/matrix/Caddyfile.matrix for the reverse-proxy block."
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# 4. Print next steps
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "🚀 Next steps:"
echo ""
echo "   1. Add Caddy/nginx config from deploy/matrix/Caddyfile.matrix"
echo "   2. Start the stack:"
echo "      docker compose -f WhatZatppa/docker-compose.matrix.yaml up -d"
echo "   3. Create an admin user:"
echo "      docker exec -it para-matrix-synapse register_new_matrix_user"
echo "         -c /data/homeserver.yaml http://localhost:8008"
echo "   4. Open https://$MATRIX_DOMAIN in a browser"
echo ""
echo "✅ Setup complete."
