#!/bin/bash
set -euo pipefail

# ═════════════════════════════════════════════════════════════════════════════
# PARA — Matrix Authentication Service setup
#
# Wires three things together:
#
#   para-idp  →  MAS  →  Synapse
#
#   para-idp   proves the user holds a PARA identity key and asserts a subject
#              (the CD-M1 localpart)
#   MAS        turns that assertion into a Matrix account and issues Matrix
#              access tokens
#   Synapse    delegates all authentication to MAS via MSC3861 and stops
#              managing passwords entirely
#
# Generates secrets into deploy/matrix/mas/ and deploy/matrix/synapse/, both
# gitignored. Run after setup.sh.
# ═════════════════════════════════════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../../.env"
MAS_DIR="${SCRIPT_DIR}/mas"
SYNAPSE_DIR="${SCRIPT_DIR}/synapse"

if [ ! -d "$SYNAPSE_DIR" ]; then
    echo "❌ ${SYNAPSE_DIR} not found. Run deploy/matrix/setup.sh first."
    exit 1
fi

if [ -f "$ENV_FILE" ]; then
    export $(grep -E '^MATRIX_' "$ENV_FILE" | xargs) || true
    export $(grep -E '^POSTGRES_' "$ENV_FILE" | xargs) || true
fi
MATRIX_SERVER_NAME="${MATRIX_SERVER_NAME:-matrix.para.social}"
POSTGRES_USER="${POSTGRES_USER:-pg}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-changeme}"

echo "═══════════════════════════════════════════════════════════════"
echo "  PARA — MAS + para-idp setup"
echo "═══════════════════════════════════════════════════════════════"

if [ -d "$MAS_DIR" ]; then
    echo "⚠️  ${MAS_DIR} already exists. Delete it to regenerate."
    exit 0
fi
mkdir -p "$MAS_DIR"

rand() { openssl rand -hex "${1:-32}"; }

# Synapse authenticates to MAS with this. MAS's convention is a fixed-shape
# client id for the homeserver.
SYNAPSE_CLIENT_ID="0000000000000000000SYNAPSE"
SYNAPSE_CLIENT_SECRET="$(rand 32)"
# MAS's admin access to Synapse.
MATRIX_SHARED_SECRET="$(rand 32)"
# MAS's own at-rest encryption key.
MAS_ENCRYPTION="$(rand 32)"
# What para-idp requires MAS to present at its token endpoint.
IDP_CLIENT_SECRET="$(rand 32)"

# MAS requires upstream provider ids to be ULIDs. Fixed rather than random so
# that regenerating config does not orphan existing account links — MAS keys
# a user's upstream link on this id, and changing it strands every account.
IDP_PROVIDER_ID="01K3ZQD8N7P0J5R2T9V4W6X8YB"

# MAS needs an RSA key for OIDC signing.
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "${MAS_DIR}/rsa.pem" 2>/dev/null
# 8 spaces: the PEM is a YAML block scalar under `key: |`, which sits at 6
# spaces, so its content must be indented deeper than its own key or the
# document fails to parse.
MAS_RSA_KEY="$(sed 's/^/        /' "${MAS_DIR}/rsa.pem")"
rm -f "${MAS_DIR}/rsa.pem"

cat > "${MAS_DIR}/config.yaml" <<MASEOF
# GENERATED by deploy/matrix/setup-mas.sh — contains secrets, do not commit.

http:
  public_base: http://localhost:8080/
  issuer: http://localhost:8080/
  listeners:
    - name: web
      resources:
        - name: discovery
        - name: human
        - name: oauth
        - name: compat
        - name: graphql
        - name: assets
      binds:
        - address: '[::]:8080'
      proxy_protocol: false
    - name: internal
      resources:
        - name: health
      binds:
        - host: 0.0.0.0
          port: 8081
      proxy_protocol: false

database:
  uri: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mas-db:5432/mas

secrets:
  encryption: ${MAS_ENCRYPTION}
  keys:
    - kid: para0001
      key: |
${MAS_RSA_KEY}

matrix:
  homeserver: ${MATRIX_SERVER_NAME}
  secret: ${MATRIX_SHARED_SECRET}
  endpoint: http://synapse:8008

clients:
  - client_id: ${SYNAPSE_CLIENT_ID}
    client_auth_method: client_secret_basic
    client_secret: ${SYNAPSE_CLIENT_SECRET}

# ─────────────────────────────────────────────────────────────────────────────
# The PARA identity provider.
#
# claims_imports.localpart action: force is the load-bearing line. para-idp's
# ID token carries sub = base32(sha256(domain ‖ identity_pub)) (CD-M1), and
# forcing it as the localpart is what makes the Matrix account name a pure
# function of client-held key material. With "suggest" the user could pick a
# different name and the property would silently not hold.
#
# Nothing else is imported: no displayname, no email. Importing a display name
# from the IdP would push a human-chosen label onto an account that is supposed
# to be unlinkable.
# ─────────────────────────────────────────────────────────────────────────────
upstream_oauth2:
  providers:
    - id: ${IDP_PROVIDER_ID}
      human_name: PARA
      issuer: http://para-idp:8090
      client_id: mas
      client_secret: ${IDP_CLIENT_SECRET}
      token_endpoint_auth_method: client_secret_post
      scope: "openid"
      discovery_mode: insecure
      pkce_method: always
      claims_imports:
        localpart:
          action: force
          template: "{{ user.sub }}"
        displayname:
          action: ignore
        email:
          action: ignore

passwords:
  # Local passwords are off. Authentication happens at para-idp, against a key
  # the server never sees. Leaving this enabled would keep a parallel way in
  # and the derived-name property would not actually be enforced.
  enabled: false

account:
  # Users cannot change their own localpart: it is derived, not chosen.
  displayname_change_allowed: true
  password_registration_enabled: false
  password_change_allowed: false
  email_change_allowed: false
  registration_token_required: false

experimental:
  access_token_ttl: 1800
MASEOF
chmod 600 "${MAS_DIR}/config.yaml"

# ─── Synapse side: delegate auth to MAS (MSC3861) ────────────────────────────
cat > "${SYNAPSE_DIR}/zz-para-msc3861.yaml" <<SYNEOF
# GENERATED by deploy/matrix/setup-mas.sh — contains secrets, do not commit.
#
# Delegates authentication to MAS. Once this is live Synapse no longer owns
# logins: the /login endpoint is disabled and clients authenticate through MAS.
experimental_features:
  msc3861:
    enabled: true
    issuer: http://mas:8080/
    client_id: ${SYNAPSE_CLIENT_ID}
    client_auth_method: client_secret_basic
    client_secret: ${SYNAPSE_CLIENT_SECRET}
    admin_token: ${MATRIX_SHARED_SECRET}
    account_management_url: http://localhost:8080/account
SYNEOF
chmod 600 "${SYNAPSE_DIR}/zz-para-msc3861.yaml"

# ─── para-idp side: the client credentials MAS will present ──────────────────
cat > "${MAS_DIR}/para-idp.env" <<IDPEOF
# GENERATED by deploy/matrix/setup-mas.sh — contains secrets, do not commit.
PARA_IDP_ISSUER=http://para-idp:8090
PARA_IDP_CLIENTS=[{"clientId":"mas","clientSecret":"${IDP_CLIENT_SECRET}","redirectUris":["http://localhost:8080/upstream/callback/${IDP_PROVIDER_ID}"]}]
IDPEOF
chmod 600 "${MAS_DIR}/para-idp.env"

echo ""
echo "✅ Generated:"
echo "   ${MAS_DIR}/config.yaml           MAS, including the PARA provider"
echo "   ${MAS_DIR}/para-idp.env          para-idp client credentials"
echo "   ${SYNAPSE_DIR}/zz-para-msc3861.yaml  Synapse auth delegation"
echo ""
echo "⚠️  All three contain secrets and are gitignored. Back them up with the"
echo "   signing key — losing them means re-linking every account."
echo ""
echo "Next:"
echo "   docker compose -f docker-compose.matrix.yaml up -d mas-db mas para-idp synapse"
echo "   docker compose -f docker-compose.matrix.yaml exec mas mas-cli database migrate"
